version: '3'
services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    networks:
      lb_network:
        ipv4_address: 10.5.0.11
    ports:
      - 3000:3000 #optional

  database:
    image: postgres:11.3
    volumes:
      - ./web-server/Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=distribuidos
      - POSTGRES_PASSWORD=javeriana
    healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "distribuidos", "-U", "distribuidos" ]
            timeout: 45s
            interval: 10s
            retries: 10
    networks:
      lb_network:
        ipv4_address: 10.5.0.3
    expose:
      - "5432"

  server1:
    image: nclsbayona/zeromq-dev:server
    networks:
      lb_network:
        ipv4_address: 10.5.0.4
    depends_on:
      database:
        condition: service_healthy
        
  server2:
    image: nclsbayona/zeromq-dev:server
    networks:
      lb_network:
        ipv4_address: 10.5.0.5
    depends_on:
      database:
        condition: service_healthy
        
  server3:
    image: nclsbayona/zeromq-dev:server
    networks:
      lb_network:
        ipv4_address: 10.5.0.6
    depends_on:
      database:
        condition: service_healthy
        
  server5:
    image: nclsbayona/zeromq-dev:server
    networks:
      lb_network:
        ipv4_address: 10.5.0.10
    depends_on:
      database:
        condition: service_healthy

  load-balancer:
    image: nclsbayona/zeromq-dev:load_balancer
    networks:
      lb_network:
        ipv4_address: 10.5.0.2
    expose:
      - "30216"
      - "8080"
    ports:
      - "80:8080"

  client1:
    image: nclsbayona/zeromq-dev:auto_client
    networks:
      lb_network:
        ipv4_address: 10.5.0.7
    depends_on:
      database:
        condition: service_healthy
        
  client2:
    image: nclsbayona/zeromq-dev:auto_client
    networks:
      lb_network:
        ipv4_address: 10.5.0.8
    depends_on:
      database:
        condition: service_healthy
        
  client3:
    image: nclsbayona/zeromq-dev:auto_client
    networks:
      lb_network:
        ipv4_address: 10.5.0.9
    depends_on:
      database:
        condition: service_healthy

networks:
  lb_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
