name: Build Container Image

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
  schedule:
    - cron: "0 0 * * */15"
  workflow_dispatch:

env:
 REGISTRY: docker.io
 IMAGE_NAME: zeromq-dev
 USERNAME:  ${{ github.actor }}

concurrency:
  group: build-${{ github.event.push.number || github.ref }}
  cancel-in-progress: true

jobs:
  base_container_build:
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build and Push Latest Docker Image
        id: build-and-push-latest
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

  lb_container_build:
    runs-on: ubuntu-latest
    needs: base_container_build
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build and Push LB Docker Image
        id: build-and-push-lb
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-load_balancer
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:load_balancer
          labels: ${{ steps.meta.outputs.labels }}
          
  client_container_build:
    runs-on: ubuntu-latest
    needs: base_container_build
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build and Push Client Docker Image
        id: build-and-push-client
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-client
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:client
          labels: ${{ steps.meta.outputs.labels }}

  autoclient_container_build:
    runs-on: ubuntu-latest
    needs: base_container_build
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build and Push Auto Client Docker Image
        id: build-and-push-auto_client
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-auto_client
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:auto_client
          labels: ${{ steps.meta.outputs.labels }}

  server_container_build:
    runs-on: ubuntu-latest
    needs: base_container_build
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build and Push Server Docker Image
        id: build-and-push-server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-server
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:server
          labels: ${{ steps.meta.outputs.labels }}
